Site\NewsBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        content:
            type: text
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: news
            joinColumn:
                name: category_id
                referencedColumnName: id              
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: news
            joinTable:
                name: tag_to_news
                joinColumns:
                    news_id: 
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id              
            
    lifecycleCallbacks: {  }

