services:
    sonata.admin.news:
        class: Site\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "News" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]
            
    sonata.admin.category:
        class: Site\NewsBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]
            
    sonata.admin.tag:
        class: Site\NewsBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tag" }
        arguments:
            - ~
            - Site\NewsBundle\Entity\Tag
            - ~
        calls:
            - [ setTranslationDomain, [SiteNewsBundle]]
